ci: refactor

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -54,12 +54,18 @@ jobs:
       - name: Install Vercel CLI
         run: npm install --global vercel@latest
 
+      - name: Link Vercel Project
+        run: |
+          echo '{"projectId":"$VERCEL_PROJECT_ID","orgId":"$VERCEL_ORG_ID"}' > .vercel/project.json
+
       - name: Pull Vercel Environment Information
         run: |
-          vercel pull --yes --environment=preview \
+          if ! vercel pull --yes --environment=preview \
             --token=$VERCEL_TOKEN \
-            --scope=$VERCEL_ORG_ID \
-            --project=$VERCEL_PROJECT_ID
+            --scope=$VERCEL_ORG_ID; then
+            echo "::error::Failed to pull Vercel environment"
+            exit 1
+          fi
         env:
           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
 
